### ISSUE TITLE
Hi Can we have a little help?

### ISSUE THREAD

**Issue by justauser001** [Wertzui123/PMMP5Converter#1]
Hi, Can You Write A Short Note Or A Video So We Can Understand How To Use This Properly

**Comment by Wertzui123** [comment]
Well, it's mostly explained in the README, just run this command in a terminal:
```bash
php converter.php /path/to/your/plugin
```
where `/path/to/your/plugin` is the path to your folder plugin.

The script will then convert a lot of PM4 code to PM5 in your plugin, but you will most likely need to do some manual conversion as well.
