### ISSUE TITLE
How use? 

### ISSUE THREAD

**Issue by ProGames7569** [Wertzui123/PMMP5Converter#2]
How use?

**Comment by ProGames7569** [comment]
Я не понимаю как использовать это.... 
Это юзать на сервере или на ПК как-то?

**Comment by Wertzui123** [comment]
See #1

You can use this script on a server or on a PC, it doesn't really matter; note that it is a standalone program and not a plugin though.

Also, I don't speak Russian, so please use a translator next time.

**Comment by Diedman9T** [comment]
> Я не понимаю как использовать это.... Это юзать на сервере или на ПК как-то?

Разобрался?

**Comment by Wertzui123** [comment]
> > Я не понимаю как использовать это.... Это юзать на сервере или на ПК как-то?
> 
> Разобрался?

As I already mentioned in my comment from June 2023, you can use this script on a server or on a PC, it doesn't really matter; note that it is a standalone program and not a plugin though.
